import Head from 'next/head';
import { Heading } from '@chakra-ui/react';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<div>
					<h1 className='text-4xl'>Hello Tailwind!</h1>
					<Heading as='h2' size='2xl'>
						Hello Chakra
					</Heading>
				</div>
			</main>
		</>
	);
}
